
work_dir: "/home/antton/Tiny_Projects/tidyGenomeBrowser_test/"  # Path to the working directory

gwas_dir: "/home/antton/Tiny_Projects/tidyGenomeBrowser_test/data/GWAS"  # Directory containing the .gwas files